// Single source of truth for all NIKKE character names.
// Used by the worker (for the AI prompt) and injected into the page at serve time.
// Add new characters here only — both will update automatically.

export const CHARACTERS = [
  "2B",
  "A2",
  "Ada Wong",
  "Ade", "Ade: Agent Bunny",
  "Admi",
  "Alice", "Alice: Wonderland Bunny",
  "Anchor", "Anchor: Innocent Maid",
  "Anis", "Anis: Sparkling Summer",
  "Anne: Miracle Fairy",
  "Arcana",
  "Aria",
  "Asuka Shikinami Langley", "Asuka Shikinami Langley: Wille",
  "Bay",
  "Belorta",
  "Biscuit",
  "Blanc",
  "Bready",
  "Brid", "Brid: Silent Track",
  "Centi",
  "Chime",
  "Chisato Nishikigi",
  "Cinderella",
  "Claire Redfield",
  "Clay",
  "Cocoa",
  "Crow",
  "Crown",
  "D", "D:Killer Wife",
  "Delta", "Delta: Ninja Thief",
  "Diesel", "Diesel: Winter Sweets",
  "Dolla",
  "Dorothy", "Dorothy: Serendipity",
  "Drake",
  "E.H.",
  "Ein",
  "Elegg", "Elegg: Boom and Shock",
  "Emilia",
  "Emma", "Emma: Tactical Upgrade",
  "Epinel",
  "Ether",
  "Eunhwa", "Eunhwa: Tactical Upgrade",
  "Eve",
  "Exia",
  "Flora",
  "Folkwang",
  "Frima",
  "Grave",
  "Guillotine", "Guillotine Winter Slayer",
  "Guilty",
  "Harran",
  "Helm", "Helm: Aquamarine",
  "Himeno",
  "Isabel",
  "Jackal",
  "Jill Valentine",
  "Julia",
  "K",
  "Kilo",
  "Kurumi",
  "Label",
  "Laplace",
  "Leona",
  "Liberalio",
  "Lily",
  "Liter",
  "Little Mermaid (Siren)",
  "Ludmilla", "Ludmilla: Winter Owner",
  "Maiden", "Maiden: Ice Rose",
  "Makima",
  "Mana",
  "Marciana",
  "Mari Makinami Illustrious",
  "Mary", "Mary: Bay Goddess",
  "Mast", "Mast: Romantic Maid",
  "Maxwell",
  "Mica", "Mica: Snow Buddy",
  "Mihara", "Mihara: Bonding Chain",
  "Milk", "Milk: Blooming Bunny",
  "Miranda",
  "Misato Katsuragi",
  "Modernia",
  "Moran",
  "Mori",
  "N102",
  "Naga",
  "Nayuta",
  "Neon", "Neon: Blue Ocean",
  "Nero",
  "Neve",
  "Nihilister",
  "Noah",
  "Noir",
  "Noise",
  "Novel",
  "Pascal",
  "Pepper",
  "Phantom",
  "Poli",
  "Power",
  "Prima",
  "Privaty", "Privaty: Unkind Maid",
  "Product08", "Product12", "Product23",
  "Quency", "Quency: Escape Queen",
  "Quiry",
  "Rapi", "Rapi: Red Hood",
  "Rapunzel", "Rapunzel: Pure Grace",
  "Raven",
  "Red Hood",
  "Rei",
  "Rei Ayanami", "Rei Ayanami (Tentative Name)",
  "Rem",
  "Rosanna", "Rosanna: Chic Ocean",
  "Rouge",
  "Rumani",
  "Rupee", "Rupee: Winter Shopper",
  "Sakura", "Sakura: Bloom in Summer",
  "Sakura Suzuhara",
  "Scarlet", "Scarlet: Black Shadow",
  "Signal",
  "Sin",
  "Snow White", "Snow White: Heavy Arms", "Snow White: Innocent Days",
  "Soda", "Soda: Twinkeling Bunny",
  "Soldier EG", "Soldier FA", "Soldier OW",
  "Soline", "Soline: Frost Ticket",
  "Sora",
  "Sugar",
  "Takina Inoue",
  "Tia",
  "Tove",
  "Trina",
  "Trony",
  "Velvet",
  "Vesti", "Vesti: Tactical Upgrade",
  "Viper",
  "Volume",
  "Yan",
  "Yulha",
  "Yuni",
  "Zwei",
  "iDoll Flower", "iDoll Ocean", "iDoll Sun",
].filter((v, i, a) => a.indexOf(v) === i).sort((a, b) => a.localeCompare(b));
